   CREATE TABLE IF NOT EXISTS assignments (
                    meta_Archived TEXT,
                    meta_CreatedAtUtc TIMESTAMP,
                    meta_Email TEXT,
                    meta_Id BIGINT PRIMARY KEY,
                    meta_InterviewsCount BIGINT,
                    meta_IsAudioRecordingEnabled BOOLEAN,
                    meta_Password TEXT,
                    meta_Quantity BIGINT,
                    meta_QuestionnaireId TEXT,
                    meta_ReceivedByTabletAtUtc TIMESTAMP,
                    meta_ResponsibleId TEXT,
                    meta_ResponsibleName TEXT,
                    meta_TargetArea TEXT,
                    meta_UpdatedAtUtc TIMESTAMP,
                    meta_WebMode BOOLEAN,
                    preload_A0 TEXT,
                    preload_A01 TEXT,
                    preload_A10 TEXT,
                    preload_A11a TEXT,
                    preload_A11b TEXT,
                    preload_A12a TEXT,
                    preload_A12b TEXT,
                    preload_A13 TEXT,
                    preload_A14a TEXT,
                    preload_A15 BIGINT,
                    preload_A1a TEXT,
                    preload_A1b BIGINT,
                    preload_A2a TEXT,
                    preload_A2b BIGINT,
                    preload_A3a TEXT,
                    preload_A3b BIGINT,
                    preload_B7 TEXT,
                    preload_B8 TEXT
                );