SURVEY_URL="https://acsl2025-demo.mysurvey.solutions"
API_USER ="siva"
API_PASSWORD="Test_12345"
API_Workspace="primary"

questionniare_variable="SriLanka_AgCensus2025"

DB_HOST = "localhost"
DB_USER = "postgres"
DB_PASSWORD = "Test_12345"
DB_PORT = "5432"
DB_NAME="ACSL2026"